import { idNumber, type WorkMetadata } from "./model.js";

const STATUS_ORDER = [
  "active",
  "ready",
  "verify",
  "waiting",
  "inbox",
  "done",
  "cancelled",
] as const;

function escapeCell(value: string): string {
  return value.replaceAll("|", "\\|").replaceAll("\n", " ");
}

function renderTable(title: string, metadata: WorkMetadata[]): string {
  const sorted = [...metadata].sort((left, right) => {
    const status =
      STATUS_ORDER.indexOf(left.status) - STATUS_ORDER.indexOf(right.status);
    return status || idNumber(left.id) - idNumber(right.id);
  });
  const rows = sorted.map(
    (item) =>
      `| [${item.id}](../work/${item.id}/overview.md) | ${escapeCell(item.title)} | ${item.status} | ${item.updated} |`,
  );
  return `# ${title}

> Generated by AIongside. Do not edit directly. Run \`aiongside view rebuild\` to restore.

| ID | Title | Status | Updated |
| --- | --- | --- | --- |
${rows.join("\n")}${rows.length ? "\n" : ""}`;
}

export function renderViews(metadata: WorkMetadata[]): Record<string, string> {
  const open = metadata.filter(
    (item) => item.status !== "done" && item.status !== "cancelled",
  );
  const closed = metadata.filter(
    (item) => item.status === "done" || item.status === "cancelled",
  );
  return {
    "views/open.md": renderTable("Open Work", open),
    "views/closed.md": renderTable("Closed Work", closed),
  };
}
