import { idNumber, type WorkRecord } from "./model.js";

const STATUS_ORDER = [
  "active",
  "ready",
  "verify",
  "waiting",
  "inbox",
  "done",
  "cancelled",
] as const;

function escapeCell(value: string): string {
  return value.replaceAll("|", "\\|").replaceAll("\n", " ");
}

function renderTable(title: string, records: WorkRecord[]): string {
  const sorted = [...records].sort((left, right) => {
    const status =
      STATUS_ORDER.indexOf(left.status) - STATUS_ORDER.indexOf(right.status);
    return status || idNumber(left.id) - idNumber(right.id);
  });
  const rows = sorted.map(
    (record) =>
      `| [${record.id}](../work/${record.id}/brief.md) | ${escapeCell(record.title)} | ${record.status} | ${record.updated} |`,
  );
  return `# ${title}

> Generated by AIongside. Do not edit directly.

| ID | Title | Status | Updated |
| --- | --- | --- | --- |
${rows.join("\n")}${rows.length ? "\n" : ""}`;
}

export function renderViews(records: WorkRecord[]): Record<string, string> {
  const open = records.filter(
    (record) => record.status !== "done" && record.status !== "cancelled",
  );
  const closed = records.filter(
    (record) => record.status === "done" || record.status === "cancelled",
  );
  return {
    "views/open.md": renderTable("Open Work", open),
    "views/closed.md": renderTable("Closed Work", closed),
  };
}
